http:
  port: 8081
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
  cust:
    host: localhost
    paths: '/api/customers/*'
  product:
    host: localhost
    paths: '/api/products'
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  cust:
    url: 'http://localhost:4000'
  product:
    url: 'http://localhost:3000'  
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
  default-1:
    apiEndpoints:
      - 'cust'
    policies:
      - proxy:
          - action:
              serviceEndpoint: 'custsrv'
  default-2:
    apiEndpoints:
      - 'product'
    policies:
      - proxy:
          - action:
              serviceEndpoint: 'prodsrv'
